Check if the event is upcoming or not
ahmetws/swifttube pull request #40
Opened 2019-07-04 21:17 UTC by aralatpulat

#35

2019-07-05 06:23 UTC, ahmetws commented on Resources/Views/event.leaf
> +                <b>#(event.fullname)</b> will take place on <b>#date(event.startDate, "yyyy/MM/dd")</b>. There are no videos for the event right now.
indentaton

2019-07-05 06:23 UTC, ahmetws commented on Resources/Views/event.leaf
>                  There are no videos for <b>#(event.fullname)</b> right now.<br/> We are working hard to add new videos and we hope they will be here soon.
indentaton

2019-07-05 06:25 UTC, ahmetws commented on Resources/Views/event.leaf
> +                #if(isUpcoming){
space after )

2019-07-05 06:25 UTC, ahmetws commented on Resources/Views/videosSection.leaf
> +                    #if(isUpcoming){
space after (

2019-07-05 06:26 UTC, ahmetws commented on Resources/Views/videosSection.leaf
> +                    } else{
space after else

2019-07-05 06:29 UTC, ahmetws commented on Sources/App/routes.swift
> +                    let context = EventContext(videos: videos, event: event!, isUpcoming: event!.isUpcoming)
should we use ! for the event

2019-07-05 06:31 UTC, ahmetws requested changes
Merge request title should explain the work done in the merge.

2019-07-06 13:50 UTC, ahmetws commented on Sources/App/routes.swift
> +                guard let eventId = event._id else {
please combine this two in a guard

2019-07-10 17:04 UTC, aralatpulat commented on Sources/App/routes.swift
> +                guard let eventId = event._id else {
combined.

2019-07-12 01:28 UTC, ahmetws approved these changes

2019-07-12 17:25 UTC, merged